### ISSUE TITLE
game_array_test.py: Typing "i" (for "inventory") crashes the game.

### ISSUE THREAD

**Issue by kfogel** [SHNIBBLES/Independent_Study_Sem1#7]
I tried out the latest version of the code (commit 591723c4ecd0a) with Python 3.7.5 on a Debian GNU/Linux system.  Below is a transcript.  The bug is that when I typed "i" to see my inventory, it crashed the game.

```
$ ./game_array_test.py 
|---------------------------------|
| Welcome to The Test Array Game! |
|           Alpha V1.0            |
|   By Elijah Underhill-Miller    |
|---------------------------------|
|--------------------|
|   Instructions:    |
| Find your way out. |
|--------------------|
|-----------------------------------------|
|                Commands:                |
|         n, e, s, w, = Movement          |
|         l = Look, i = Inventory         |
| If you wish to interact with an object, |
|             type its name.              |
|-----------------------------------------|
You slowly open your eyes, you're in the corner of a dimly lit room.
--> l
You inspect the room further- 
--> l
You inspect the room further- 
--> i
| Inventory: 
Traceback (most recent call last):
  File "./game_array_test.py", line 187, in <module>
    for x in range(inventory):
NameError: name 'inventory' is not defined
$ 
```

**Comment by SHNIBBLES** [comment]
Fixed this in the latest commit

**Comment by kfogel** [comment]
Great!  Some tips:

When a commit fixes a bug, mention the bug number in the commit message, with a phrase like "fixes issue #7".  That allows the bug tracker and the repository to coordinate with each other -- this ticket would automatically get a notice.

Second, when you mention a commit (like in your comment above), usually it's a good idea to give the commit ID.  See my first comment in this ticket, for example.  Do you know how to find the commit ID using `git log`?  Tell me which commit it was and I'll go look right now.

(I mean, I'll look at all your recent commits anyway, but I'd want to look at this particular one first -- only I need to know its ID so I can find it :-) .)

**Comment by SHNIBBLES** [comment]
The commit ID was 63bc6c75af73dbf6588507ad4000f2548006fbed

**Comment by SHNIBBLES** [comment]
Also, if I have multiple files to commit at once is it possible to have different messages for each one?

**Comment by kfogel** [comment]
Nope; commit messages are per-commit.  However, your message can be multiple lines long and discuss the different changes to the different files.  When you're going to write a commit message that's more than one line -- most of them are more than one line -- then just write the message in a file and pass the file when you commit, like this: `git commit -F message_file`.

This is a great post on writing commit messages: https://chris.beams.io/posts/git-commit/

**Comment by kfogel** [comment]
Right now your commit messages are one really long line :-).  But see that post above: if you format them in a certain way, they get easier to work with later when you need to go back and read them (which is what I'm doing in real-time as you code).
